# Generated by Django 2.2.6 on 2020-04-24 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20200424_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageinfo',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
